### ISSUE TITLE
Update to version 1.9.5

### ISSUE THREAD

**Issue by rroblak** [wmdietl/jsr308-langtools#1]
Version 1.9.5 is available in the upstream repo: https://bitbucket.org/typetools/jsr308-langtools/commits/fc9023ec7fab

**Comment by wmdietl** [comment]
Thanks for letting us know! There was a mix-up in the release process. I've pushed the missing tag. We're working on unifying the two repositories for the upcoming release.

**Comment by rroblak** [comment]
Great, thanks @wmdietl.
